apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: rayjob-landing
spec:
  entrypoint: python /app/main.py --mode "ray" --stage "landing" --source_folder "/resources" --dest_folder "test/ray"
  submitterPodTemplate:
    spec:
      restartPolicy: Never
      containers:
      - name: ray-job
        image: raydemo.azurecr.io/ray-actor-example:latest
        volumeMounts:
        - mountPath: /home/ray/.azure
          name: azure-cli-creds
      volumes:
      - name: azure-cli-creds
        hostPath:
          path: /home/azureuser/.azure
          type: Directory


  # rayClusterSpec specifies the RayCluster instance to be created by the RayJob controller.
  rayClusterSpec:
    rayVersion: '2.46.0' # should match the Ray version in the image of the containers
    headGroupSpec:
      template:
        spec:
          containers:
          - name: ray-head
            image: raydemo.azurecr.io/ray-actor-example:latest
            ports:
            - containerPort: 6379
              name: gcs-server
            - containerPort: 8265 # Ray dashboard
              name: dashboard
            - containerPort: 10001
              name: client
            resources:
              limits:
                cpu: "1"
              requests:
                cpu: "200m"
            env:
              - name: DX_API_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: dxpy-api-secret
                    key: DX_API_TOKEN
              - name: RAY_CONNECTION_STR
                valueFrom:
                  secretKeyRef:
                    name: ray-connection-str
                    key: RAY_CONNECTION_STR
            volumeMounts:
            - mountPath: /home/ray/.azure
              name: azure-cli-creds
          volumes:
          - name: azure-cli-creds
            hostPath:
              path: /home/azureuser/.azure
              type: Directory

    workerGroupSpecs:
    # the pod replicas in this group typed worker
    - replicas: 1
      minReplicas: 1
      maxReplicas: 5
      # logical group name, for this called small-group, also can be functional
      groupName: small-group
      template:
        spec:
          containers:
          - name: ray-worker # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc'
            image: raydemo.azurecr.io/ray-actor-example:latest
            resources:
              limits:
                cpu: "1"
              requests:
                cpu: "200m"
            env:
              - name: DX_API_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: dxpy-api-secret
                    key: DX_API_TOKEN
              - name: RAY_CONNECTION_STR
                valueFrom:
                  secretKeyRef:
                    name: ray-connection-str
                    key: RAY_CONNECTION_STR
            volumeMounts:
            - mountPath: /home/ray/.azure
              name: azure-cli-creds
          volumes:
          - name: azure-cli-creds
            hostPath:
              path: /home/azureuser/.azure
              type: Directory