kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /home/azureuser/.azure   # local path on your machine
    containerPath: /home/azureuser/.azure      # path inside the kind node container
