    apiVersion: v1
    kind: Service
    metadata:
      name: azurite
    spec:
      selector:
        app: azurite
      ports:
      - name: blob
        protocol: TCP
        port: 10000
        targetPort: 10000
      - name: queue
        protocol: TCP
        port: 10001
        targetPort: 10001
      - name: table
        protocol: TCP
        port: 10002
        targetPort: 10002
      type: ClusterIP # Or NodePort/LoadBalancer for external access